services:
  mancala-postgres:
    image: "postgres:14.2-alpine"
    container_name: mancala-postgres
    volumes:
      - mancala-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 10s

  mancala-app:
    build: .
    depends_on:
      mancala-postgres:
        condition: service_healthy
        restart: true
    container_name: mancala-app
    ports:
      - 8080:8080

  mancala-ui:
    build: ./ui
    depends_on:
      mancala-app:
        condition: service_started
    container_name: mancala-ui
    ports:
      - 3000:80
volumes:
  mancala-data:
